

def check_type(x, t, msg=None):
    """
    Raises a TypeError if the given value is not of the given type.
    :param x: The value the type of which is to be checked.
    :param t: The type that the value is supposed to have.
    :param msg: The message for the TypeError to be thrown. A generic message is generated by default.
    :return: The value x.
    """
    if not isinstance(x, t):
        raise TypeError("{x} is of type {f}, but type {e} was expected!".format(x=x, f=type(x), e=t))

    return x
